// Generated by scripts/intro/generate_intro_narration.py — do not edit by hand.
// Voiceover: Mimic 3 VITS voices from https://github.com/MycroftAI/mimic3-voices
//   Korean:  ko_KO/kss_low  (KSS corpus — professional Korean voice actress, CC0)
//   English: en_US/ljspeech_low  (LJ Speech — public domain)
// Full credits: docs/INTRO_VOICE.md
window.HANAPATH_APP_INTRO_CONFIG = {
  "version": 2,
  "generated": "scripts/intro/generate_intro_narration.py",
  "audioSrc": "./audio/intro/intro_narration.ogg?v=b4f722d5",
  "duration": 55203,
  "voice": {
    "korean": "Mimic 3 VITS ko_KO/kss_low — KSS corpus (Kyubyong Park), CC0",
    "english": "Mimic 3 VITS en_US/ljspeech_low — LJ Speech, public domain",
    "source": "https://github.com/MycroftAI/mimic3-voices @ b239a9084e21"
  },
  "scenes": [
    {
      "id": "wall",
      "lines": [
        {
          "lang": "ko",
          "text": "안녕하세요!",
          "start": 449,
          "duration": 913,
          "words": [
            {
              "w": "안녕하세요!",
              "t": 449,
              "d": 913
            }
          ]
        },
        {
          "lang": "en",
          "text": "Korean can feel like a wall of unfamiliar sounds and symbols.",
          "start": 1913,
          "duration": 4114,
          "words": [
            {
              "w": "Korean",
              "t": 1913,
              "d": 484
            },
            {
              "w": "can",
              "t": 2397,
              "d": 242
            },
            {
              "w": "feel",
              "t": 2639,
              "d": 242
            },
            {
              "w": "like",
              "t": 2881,
              "d": 242
            },
            {
              "w": "a",
              "t": 3123,
              "d": 80
            },
            {
              "w": "wall",
              "t": 3203,
              "d": 242
            },
            {
              "w": "of",
              "t": 3445,
              "d": 161
            },
            {
              "w": "unfamiliar",
              "t": 3607,
              "d": 726
            },
            {
              "w": "sounds",
              "t": 4333,
              "d": 403
            },
            {
              "w": "and",
              "t": 4736,
              "d": 242
            },
            {
              "w": "symbols.",
              "t": 4978,
              "d": 1048
            }
          ]
        }
      ],
      "start": 0,
      "duration": 6358
    },
    {
      "id": "hangul",
      "lines": [
        {
          "lang": "en",
          "text": "But every language has a way in. Start with Hangul — the beautifully structured alphabet behind every Korean word.",
          "start": 6978,
          "duration": 7281,
          "words": [
            {
              "w": "But",
              "t": 6978,
              "d": 234
            },
            {
              "w": "every",
              "t": 7212,
              "d": 313
            },
            {
              "w": "language",
              "t": 7526,
              "d": 548
            },
            {
              "w": "has",
              "t": 8074,
              "d": 234
            },
            {
              "w": "a",
              "t": 8308,
              "d": 78
            },
            {
              "w": "way",
              "t": 8387,
              "d": 156
            },
            {
              "w": "in.",
              "t": 8543,
              "d": 626
            },
            {
              "w": "Start",
              "t": 9170,
              "d": 391
            },
            {
              "w": "with",
              "t": 9561,
              "d": 234
            },
            {
              "w": "Hangul",
              "t": 9796,
              "d": 469
            },
            {
              "w": "—",
              "t": 10266,
              "d": 78
            },
            {
              "w": "the",
              "t": 10344,
              "d": 156
            },
            {
              "w": "beautifully",
              "t": 10501,
              "d": 626
            },
            {
              "w": "structured",
              "t": 11127,
              "d": 626
            },
            {
              "w": "alphabet",
              "t": 11753,
              "d": 548
            },
            {
              "w": "behind",
              "t": 12301,
              "d": 469
            },
            {
              "w": "every",
              "t": 12771,
              "d": 313
            },
            {
              "w": "Korean",
              "t": 13084,
              "d": 469
            },
            {
              "w": "word.",
              "t": 13554,
              "d": 704
            }
          ]
        },
        {
          "lang": "ko",
          "text": "한글!",
          "start": 14660,
          "duration": 702,
          "words": [
            {
              "w": "한글!",
              "t": 14660,
              "d": 702
            }
          ]
        }
      ],
      "start": 6358,
      "duration": 9334
    },
    {
      "id": "words",
      "lines": [
        {
          "lang": "en",
          "text": "Build vocabulary you can recognise, hear, and remember.",
          "start": 16312,
          "duration": 4121,
          "words": [
            {
              "w": "Build",
              "t": 16312,
              "d": 311
            },
            {
              "w": "vocabulary",
              "t": 16623,
              "d": 855
            },
            {
              "w": "you",
              "t": 17478,
              "d": 155
            },
            {
              "w": "can",
              "t": 17633,
              "d": 233
            },
            {
              "w": "recognise,",
              "t": 17867,
              "d": 855
            },
            {
              "w": "hear,",
              "t": 18722,
              "d": 466
            },
            {
              "w": "and",
              "t": 19188,
              "d": 233
            },
            {
              "w": "remember.",
              "t": 19422,
              "d": 1010
            }
          ]
        }
      ],
      "start": 15692,
      "duration": 5072
    },
    {
      "id": "sentences",
      "lines": [
        {
          "lang": "en",
          "text": "Then bring those words together, until real Korean sentences begin to make sense.",
          "start": 21384,
          "duration": 5812,
          "words": [
            {
              "w": "Then",
              "t": 21384,
              "d": 264
            },
            {
              "w": "bring",
              "t": 21648,
              "d": 352
            },
            {
              "w": "those",
              "t": 22000,
              "d": 264
            },
            {
              "w": "words",
              "t": 22264,
              "d": 352
            },
            {
              "w": "together,",
              "t": 22616,
              "d": 792
            },
            {
              "w": "until",
              "t": 23409,
              "d": 440
            },
            {
              "w": "real",
              "t": 23849,
              "d": 264
            },
            {
              "w": "Korean",
              "t": 24113,
              "d": 528
            },
            {
              "w": "sentences",
              "t": 24642,
              "d": 792
            },
            {
              "w": "begin",
              "t": 25434,
              "d": 440
            },
            {
              "w": "to",
              "t": 25875,
              "d": 176
            },
            {
              "w": "make",
              "t": 26051,
              "d": 264
            },
            {
              "w": "sense.",
              "t": 26315,
              "d": 880
            }
          ]
        },
        {
          "lang": "ko",
          "text": "저는 한국어를 배워요.",
          "start": 27646,
          "duration": 1576,
          "words": [
            {
              "w": "저는",
              "t": 27646,
              "d": 394
            },
            {
              "w": "한국어를",
              "t": 28040,
              "d": 675
            },
            {
              "w": "배워요.",
              "t": 28715,
              "d": 506
            }
          ]
        }
      ],
      "start": 20764,
      "duration": 8788
    },
    {
      "id": "system",
      "lines": [
        {
          "lang": "en",
          "text": "HanaPath guides you forward with focused lessons, intelligent review, and a clear view of your progress.",
          "start": 30172,
          "duration": 6653,
          "words": [
            {
              "w": "HanaPath",
              "t": 30172,
              "d": 554
            },
            {
              "w": "guides",
              "t": 30726,
              "d": 316
            },
            {
              "w": "you",
              "t": 31043,
              "d": 158
            },
            {
              "w": "forward",
              "t": 31201,
              "d": 475
            },
            {
              "w": "with",
              "t": 31676,
              "d": 237
            },
            {
              "w": "focused",
              "t": 31914,
              "d": 475
            },
            {
              "w": "lessons,",
              "t": 32389,
              "d": 712
            },
            {
              "w": "intelligent",
              "t": 33102,
              "d": 792
            },
            {
              "w": "review,",
              "t": 33894,
              "d": 633
            },
            {
              "w": "and",
              "t": 34528,
              "d": 237
            },
            {
              "w": "a",
              "t": 34765,
              "d": 79
            },
            {
              "w": "clear",
              "t": 34844,
              "d": 316
            },
            {
              "w": "view",
              "t": 35161,
              "d": 237
            },
            {
              "w": "of",
              "t": 35399,
              "d": 158
            },
            {
              "w": "your",
              "t": 35557,
              "d": 237
            },
            {
              "w": "progress.",
              "t": 35795,
              "d": 1029
            }
          ]
        }
      ],
      "start": 29552,
      "duration": 7554
    },
    {
      "id": "mantra",
      "lines": [
        {
          "lang": "en",
          "text": "Learn.",
          "start": 37726,
          "duration": 380,
          "words": [
            {
              "w": "Learn.",
              "t": 37726,
              "d": 380
            }
          ]
        },
        {
          "lang": "en",
          "text": "Practice.",
          "start": 38656,
          "duration": 895,
          "words": [
            {
              "w": "Practice.",
              "t": 38656,
              "d": 895
            }
          ]
        },
        {
          "lang": "en",
          "text": "Progress.",
          "start": 40101,
          "duration": 914,
          "words": [
            {
              "w": "Progress.",
              "t": 40101,
              "d": 914
            }
          ]
        }
      ],
      "start": 37106,
      "duration": 4240
    },
    {
      "id": "possible",
      "lines": [
        {
          "lang": "en",
          "text": "One step at a time, Korean stops looking foreign — and starts feeling possible.",
          "start": 41966,
          "duration": 5259,
          "words": [
            {
              "w": "One",
              "t": 41966,
              "d": 242
            },
            {
              "w": "step",
              "t": 42208,
              "d": 323
            },
            {
              "w": "at",
              "t": 42532,
              "d": 161
            },
            {
              "w": "a",
              "t": 42694,
              "d": 80
            },
            {
              "w": "time,",
              "t": 42775,
              "d": 485
            },
            {
              "w": "Korean",
              "t": 43260,
              "d": 485
            },
            {
              "w": "stops",
              "t": 43745,
              "d": 404
            },
            {
              "w": "looking",
              "t": 44150,
              "d": 404
            },
            {
              "w": "foreign",
              "t": 44555,
              "d": 404
            },
            {
              "w": "—",
              "t": 44959,
              "d": 80
            },
            {
              "w": "and",
              "t": 45040,
              "d": 242
            },
            {
              "w": "starts",
              "t": 45283,
              "d": 485
            },
            {
              "w": "feeling",
              "t": 45768,
              "d": 404
            },
            {
              "w": "possible.",
              "t": 46173,
              "d": 1051
            }
          ]
        }
      ],
      "start": 41346,
      "duration": 6260
    },
    {
      "id": "welcome",
      "lines": [
        {
          "lang": "en",
          "text": "Welcome to HanaPath. Your path starts here.",
          "start": 48226,
          "duration": 3015,
          "words": [
            {
              "w": "Welcome",
              "t": 48226,
              "d": 430
            },
            {
              "w": "to",
              "t": 48656,
              "d": 143
            },
            {
              "w": "HanaPath.",
              "t": 48800,
              "d": 933
            },
            {
              "w": "Your",
              "t": 49733,
              "d": 215
            },
            {
              "w": "path",
              "t": 49948,
              "d": 215
            },
            {
              "w": "starts",
              "t": 50164,
              "d": 430
            },
            {
              "w": "here.",
              "t": 50594,
              "d": 646
            }
          ]
        },
        {
          "lang": "ko",
          "text": "시작해 볼까요?",
          "start": 51692,
          "duration": 1111,
          "words": [
            {
              "w": "시작해",
              "t": 51692,
              "d": 529
            },
            {
              "w": "볼까요?",
              "t": 52221,
              "d": 581
            }
          ]
        }
      ],
      "start": 47606,
      "duration": 7597
    }
  ],
  "chips": {
    "안녕하세요": {
      "src": "./audio/intro/chip_209bebae3e.ogg?v=b0f78cf6",
      "ms": 947
    },
    "괜찮아요": {
      "src": "./audio/intro/chip_b9b7062380.ogg?v=76633e72",
      "ms": 873
    },
    "한국어": {
      "src": "./audio/intro/chip_d6d014c612.ogg?v=0d9e4244",
      "ms": 926
    },
    "사랑": {
      "src": "./audio/intro/chip_1be29cfd1c.ogg?v=e0121d70",
      "ms": 502
    },
    "배우다": {
      "src": "./audio/intro/chip_4881c2b3d3.ogg?v=358e2377",
      "ms": 679
    },
    "오늘": {
      "src": "./audio/intro/chip_e1e8a7b402.ogg?v=88eba97e",
      "ms": 298
    },
    "문장": {
      "src": "./audio/intro/chip_46da162d0b.ogg?v=ddb4daab",
      "ms": 623
    },
    "기억": {
      "src": "./audio/intro/chip_3204ca3181.ogg?v=16b8bcf2",
      "ms": 363
    },
    "한국": {
      "src": "./audio/intro/chip_afd6d52f98.ogg?v=15c05f35",
      "ms": 405
    },
    "말하다": {
      "src": "./audio/intro/chip_7109575bcb.ogg?v=aa43a8ec",
      "ms": 720
    },
    "시작": {
      "src": "./audio/intro/chip_82e5f38632.ogg?v=d5112a86",
      "ms": 495
    },
    "한글": {
      "src": "./audio/intro/chip_52b8c54ab4.ogg?v=8a29e45b",
      "ms": 821
    },
    "사람": {
      "src": "./audio/intro/chip_61738cb6ca.ogg?v=a3a74ee1",
      "ms": 408
    },
    "물": {
      "src": "./audio/intro/chip_3558e19de4.ogg?v=24433439",
      "ms": 250
    },
    "먹다": {
      "src": "./audio/intro/chip_a8d7fa09a2.ogg?v=8464b99a",
      "ms": 427
    },
    "가다": {
      "src": "./audio/intro/chip_efb0dbba29.ogg?v=ec52e4b5",
      "ms": 394
    },
    "가요": {
      "src": "./audio/intro/chip_5b6f1cd332.ogg?v=c4a1e1c9",
      "ms": 324
    },
    "갔어요": {
      "src": "./audio/intro/chip_ffa38ff23f.ogg?v=1d48a07f",
      "ms": 519
    },
    "저는": {
      "src": "./audio/intro/chip_9bad4e9179.ogg?v=eb826b9d",
      "ms": 383
    },
    "한국어를": {
      "src": "./audio/intro/chip_5887b3b2b5.ogg?v=253e8c71",
      "ms": 784
    },
    "배워요": {
      "src": "./audio/intro/chip_e2fe6c73d9.ogg?v=511e31f9",
      "ms": 681
    },
    "저는 한국어를 배워요.": {
      "src": "./audio/intro/chip_35d6b4f4fc.ogg?v=0a0a97d8",
      "ms": 1540
    },
    "한": {
      "src": "./audio/intro/chip_f7ad7dea32.ogg?v=171b4df2",
      "ms": 182
    },
    "국": {
      "src": "./audio/intro/chip_e718ce8ae5.ogg?v=be2ae6bd",
      "ms": 207
    },
    "어": {
      "src": "./audio/intro/chip_60e3b21d67.ogg?v=1fa69ba8",
      "ms": 208
    },
    "를": {
      "src": "./audio/intro/chip_11a5c5a48d.ogg?v=34e285ab",
      "ms": 258
    },
    "배": {
      "src": "./audio/intro/chip_494a1a8616.ogg?v=b0679458",
      "ms": 176
    },
    "워": {
      "src": "./audio/intro/chip_0248bc2c0b.ogg?v=bef663a6",
      "ms": 286
    },
    "요": {
      "src": "./audio/intro/chip_e3eb0dfb0d.ogg?v=3f4baa4d",
      "ms": 233
    },
    "시작해 볼까요?": {
      "src": "./audio/intro/chip_f7d513a6c5.ogg?v=5dc5fe50",
      "ms": 1229
    },
    "하나": {
      "src": "./audio/intro/chip_558136bd17.ogg?v=024605a6",
      "ms": 399
    }
  }
};
