// Real English meanings for the raw 5,000-word frequency list.
// Plain static browser global — no modules, no build step. Loaded before app.js.
//
// The raw list is an un-lemmatized frequency count: it contains full content
// words alongside particles, verb/adjective stems, and endings (exactly as
// documented in docs/WORDS_SECTION_MASTER_SPEC.md). Rather than inventing a
// fake simple-noun gloss for a fragment like "하" (the stem of 하다, not a
// standalone word), each entry here is labeled honestly for what it actually
// is. This does NOT replace curated lessons — it only gives every raw entry
// a real meaning for search/reference, distinct from the fuller curated
// entries (which add examples, audio, and usage notes).
//
// Coverage: ranks 1-500 (the app's existing "1-500" frequency band) as a
// first pass. Remaining ranks still show as reference-only with no invented
// meaning, same as before.
(function () {
  "use strict";

  window.HANAPATH_RAW_MEANINGS = {
    "이": "this / subject particle (very common, multiple functions)",
    "는": "topic particle",
    "을": "object particle",
    "하": "stem of 하다 (to do)",
    "에": "at / to (place or time particle)",
    "다": "plain-style sentence ending (verb/adjective dictionary form)",
    "의": "possessive particle (of, 's)",
    "고": "and, and then (connects verbs)",
    "은": "topic particle (after consonant)",
    "가": "subject particle (after vowel)",
    "를": "object particle (after vowel)",
    "있": "stem of 있다 (to exist, to have)",
    "들": "plural marker suffix",
    "한": "one (determiner); also stem of 하다",
    "도": "also, too (particle)",
    "어": "verb/adjective ending (informal, or connects clauses)",
    "게": "adverb-forming ending (e.g. 크게 = big-ly)",
    "에서": "at / from (place particle, action location)",
    "으로": "to, toward, by means of (particle)",
    "일": "day; work; one (number)",
    "나": "I, me (casual); or (particle)",
    "로": "to, toward, by means of (particle, after vowel)",
    "지": "negative/continuous verb ending",
    "했": "did (past stem of 하다)",
    "었": "past tense marker",
    "해": "do (casual/contracted form of 하다)",
    "아": "verb/adjective ending (informal, vowel-harmony form)",
    "과": "and, with (particle, after consonant)",
    "되": "stem of 되다 (to become)",
    "기": "noun-forming ending (turns a verb into a noun)",
    "것": "thing (dependent noun)",
    "그": "that (determiner)",
    "수": "way, ability (as in 할 수 있다 = to be able to)",
    "면": "if, when (conditional ending)",
    "와": "and, with (particle, after vowel)",
    "적": "-like, -ical (suffix, as in 사회적 = social)",
    "할": "to do (future/modifier form of 하다)",
    "인": "is (copula form); person (suffix, as in 한국인 = Korean person)",
    "만": "only (particle)",
    "안": "inside; not (negation)",
    "거": "thing (casual form of 것)",
    "보": "stem of 보다 (to see)",
    "요": "polite sentence-ending particle",
    "습니다": "formal polite sentence ending",
    "없": "stem of 없다 (to not exist, to not have)",
    "주": "stem of 주다 (to give)",
    "월": "month",
    "말": "speech, words; end (as in 월말 = end of month)",
    "좋": "stem of 좋다 (to be good)",
    "내": "my, inside (as in 내 = my, casual)",
    "니": "question ending (casual)",
    "않": "stem of 않다 (negation auxiliary, to not do)",
    "시": "hour; honorific infix",
    "년": "year",
    "같": "stem of 같다 (to be the same, to be like)",
    "제": "my (humble form); ordinal prefix (as in 제1 = first)",
    "입": "mouth; stem of 이다 (to be)",
    "더": "more",
    "사람": "person",
    "자": "person suffix (as in 노동자 = worker); character (as in 문자 = letter)",
    "지만": "but, although (connective ending)",
    "겠": "will, intend to (future/conjecture marker)",
    "는데": "but, and (background/contrast connective ending)",
    "야": "hey (casual address); or (as in 이야말로)",
    "여": "and (formal connective, in lists)",
    "아니": "no, not (casual negation)",
    "우리": "we, our",
    "던": "past-recollective modifier ending",
    "에게": "to (a person; particle)",
    "된": "became (modifier form of 되다)",
    "때": "time, moment",
    "라고": "quoting particle (said that...)",
    "며": "and, while (connective ending, formal)",
    "전": "before, ago",
    "네": "yes; your (casual); plural-ish suffix (우리네)",
    "라": "quoting/imperative ending",
    "한다": "does (plain present of 하다)",
    "저": "I, me (polite); that (over there)",
    "님": "honorific title suffix (Mr./Ms./esteemed)",
    "알": "stem of 알다 (to know)",
    "았": "past tense marker (vowel-harmony form)",
    "잘": "well (adverb)",
    "합니다": "does (formal polite of 하다)",
    "등": "etc., and so on",
    "까지": "until, up to (particle)",
    "받": "stem of 받다 (to receive)",
    "오": "stem of 오다 (to come)",
    "중": "during, in the middle of",
    "서": "at (contracted particle, from 에서/에게서); stand (stem of 서다)",
    "못": "cannot (negative ability adverb)",
    "생각": "thought, idea",
    "번": "counter for times/occurrences; number",
    "세요": "polite imperative/present ending (please do / does)",
    "싶": "want to (auxiliary stem, as in 먹고 싶다 = want to eat)",
    "다고": "quoting particle (said that...)",
    "개": "counter for general objects",
    "대": "counter for machines/vehicles; versus, against",
    "두": "two (native Korean number, as in 두 개)",
    "였": "was (past copula stem)",
    "시간": "time, hour",
    "면서": "while (simultaneous action connective)",
    "부터": "from, starting from (particle)",
    "성": "nature, -ness (suffix, as in 가능성 = possibility); castle",
    "분": "minute; polite counter for people",
    "라는": "called, that is called (quoting modifier)",
    "명": "counter for people; name (as in 명함)",
    "많": "stem of 많다 (to be many)",
    "원": "won (currency); source, origin",
    "살": "years old (age counter)",
    "다른": "other, different",
    "지금": "now",
    "때문": "because of",
    "어서": "so, because (connective ending); please (imperative marker)",
    "왜": "why",
    "다는": "that says / that means (quoting modifier)",
    "여자": "woman",
    "으면": "if, when (conditional ending, after consonant)",
    "뭐": "what (casual)",
    "위": "above, on top of; stomach",
    "화": "fire; anger; -ization suffix (as in 문화 = culture)",
    "좀": "a bit, please (softening adverb)",
    "해서": "so, because of doing (connective of 하다)",
    "건": "matter, thing (contracted form of 것은)",
    "죠": "right?, isn't it (casual confirming ending)",
    "하나": "one",
    "한국": "Korea",
    "후": "after",
    "같이": "together; like, as",
    "날": "day",
    "시작": "start, beginning",
    "신": "shoe; god; new (prefix)",
    "먹": "stem of 먹다 (to eat)",
    "사랑": "love",
    "그리고": "and",
    "니까": "because, since (connective ending)",
    "만들": "stem of 만들다 (to make)",
    "맞": "stem of 맞다 (to be correct, to fit)",
    "게임": "game",
    "군": "county; exclamation ending (I see!)",
    "및": "and, as well as (formal connective)",
    "사용": "use",
    "차": "car; tea; time/turn (counter)",
    "너": "you (casual)",
    "될": "to become (future/modifier form of 되다)",
    "위해": "for the sake of",
    "줄": "way, method (as in 할 줄 알다 = know how to); line, string",
    "집": "house, home",
    "함께": "together",
    "해야": "must do (obligation connective of 하다)",
    "가지": "kind, sort; branch",
    "남자": "man",
    "또": "again",
    "보다": "to see; than (comparison particle)",
    "너무": "too, too much",
    "대한": "about, concerning (modifier of 대하다)",
    "랑": "and, with (casual particle)",
    "사": "four; company (suffix, as in 회사)",
    "오늘": "today",
    "이런": "this kind of",
    "이상": "more than, above; abnormality (ambiguous)",
    "함": "doing (nominalized form of 하다)",
    "걸": "thing (contracted form of 것을)",
    "길": "road, way",
    "다시": "again",
    "데": "place, situation (dependent noun, as in 가는 데)",
    "모든": "all, every",
    "찾": "stem of 찾다 (to find, to look for)",
    "그렇": "stem of 그렇다 (to be so, to be like that)",
    "애": "child (casual, short for 아이); love (as in 애정)",
    "필요": "necessity, need",
    "된다": "becomes (plain present of 되다)",
    "문제": "problem, question",
    "서울": "Seoul",
    "해요": "does (polite present of 하다)",
    "곳": "place",
    "네요": "I see, isn't it (exclamatory/observational ending)",
    "씨": "Mr./Ms. (name title); seed",
    "정말": "really, truly",
    "죽": "stem of 죽다 (to die); porridge",
    "세": "three (native Korean number prefix); age counter",
    "아이": "child",
    "자신": "oneself, self; confidence",
    "형": "older brother (male speaker's); form, shape",
    "난": "I (contracted 나는); egg (as in 계란, ambiguous)",
    "됐": "became, is done (past of 되다, also \"that's enough\")",
    "달": "moon; month",
    "세계": "world",
    "으며": "and, while (formal connective, after consonant)",
    "이름": "name",
    "친구": "friend",
    "가장": "most (superlative)",
    "권": "counter for books; right, authority (as in 인권 = human rights)",
    "끝": "end",
    "남": "other people, stranger; south (ambiguous)",
    "다음": "next",
    "비": "rain",
    "속": "inside",
    "지역": "region, area",
    "처럼": "like, as (particle)",
    "모두": "all, everyone",
    "사실": "fact, truth",
    "아요": "polite present ending (vowel-harmony form)",
    "많이": "a lot, much",
    "바로": "right away, directly",
    "음": "hmm (interjection); sound (suffix, as in 발음 = pronunciation)",
    "한테": "to (a person; casual particle)",
    "모르": "stem of 모르다 (to not know)",
    "볼": "to see (future/modifier form of 보다)",
    "잡": "stem of 잡다 (to catch, to grab)",
    "학교": "school",
    "가능": "possibility, possible",
    "그런": "that kind of, such",
    "앞": "front",
    "간": "liver; between, interval (ambiguous)",
    "그냥": "just, simply, without a particular reason",
    "미국": "United States",
    "상": "award, prize; table; injury (ambiguous)",
    "엔": "yen (currency); in (particle, casual)",
    "이제": "now, from now on",
    "물": "water",
    "진짜": "really, genuine",
    "호": "issue number; name suffix (ambiguous)",
    "회": "time, occasion (counter); meeting (short for 회의)",
    "경우": "case, situation",
    "동안": "during, for (a period of time)",
    "으": "filler vowel before a consonant-starting particle (grammatical, no independent meaning)",
    "이렇": "stem of 이렇다 (to be like this)",
    "일본": "Japan",
    "첫": "first",
    "그러": "stem of 그러다 (to do that, to act that way)",
    "는지": "whether, if (indirect question ending)",
    "마음": "heart, mind",
    "본": "this, original (prefix); saw (past of 보다)",
    "손": "hand",
    "쓰": "stem of 쓰다 (to write, to use)",
    "예": "yes; example (short for 예시)",
    "정도": "degree, extent, about",
    "조": "billion (counter unit); group, team",
    "타": "stem of 타다 (to ride); burnt (stem of 타다, to burn)",
    "당": "per (as in 1인당 = per person); sugar; political party (ambiguous)",
    "장": "chapter; sheet (counter); place (as in 시장 = market)",
    "진": "camp; true (prefix, as in 진짜)",
    "치": "tooth (suffix); unit of measure (ambiguous)",
    "냐": "casual question ending",
    "대표": "representative",
    "도록": "so that, in order to (purpose connective)",
    "보이": "stem of 보이다 (to be seen, to appear)",
    "영화": "movie",
    "자기": "oneself, self; honey (term of endearment)",
    "대해": "about, concerning (from 대하다)",
    "뒤": "back, behind",
    "라도": "even if, at least (particle)",
    "마": "don't (negative imperative, casual, short for 말아)",
    "뿐": "only, merely",
    "사이트": "website",
    "세상": "world",
    "크": "stem of 크다 (to be big)",
    "큰": "big (modifier form of 크다)",
    "놓": "stem of 놓다 (to put down, to place)",
    "봤": "saw (past of 보다)",
    "부": "part, section; department; negative prefix (ambiguous)",
    "셨": "honorific past tense marker",
    "여기": "here",
    "당신": "you (formal/distant, or intimate between spouses)",
    "돈": "money",
    "실": "room (suffix, as in 교실); thread; loss (ambiguous)",
    "어떤": "what kind of, which",
    "눈": "eye; snow",
    "다가": "while, in the middle of doing (connective ending)",
    "다면": "if (conditional connective)",
    "따라": "according to, following (from 따르다)",
    "어떻": "stem of 어떻다 (to be how)",
    "왔": "came (past of 오다)",
    "째": "-th (ordinal suffix, as in 두 번째 = second)",
    "처음": "the first time",
    "팀": "team",
    "또한": "also, furthermore",
    "봐": "see! look! (casual imperative/present of 보다)",
    "아서": "so, because (connective ending, vowel-harmony form)",
    "이번": "this time",
    "이야기": "story, talk",
    "이유": "reason",
    "밖": "outside",
    "열": "heat, fever; ten (native Korean number)",
    "인데": "but, and (background connective, copula form)",
    "키": "height; key (loanword, ambiguous)",
    "감사": "thanks, gratitude",
    "또는": "or",
    "밤": "night; chestnut (ambiguous)",
    "불": "fire, light",
    "사진": "photo",
    "선": "line; pre- (prefix, as in 선생님)",
    "소리": "sound",
    "스": "part of a loanword suffix (e.g. 서비스 = service); no independent meaning alone",
    "안전": "safety",
    "여성": "woman, female",
    "온": "came (past modifier of 오다); all, whole (as in 온 세상)",
    "현재": "the present, now",
    "거나": "or (connects verb choices)",
    "계속": "continuously, keep on",
    "미": "beauty (prefix/suffix, as in 미국 short form); not yet (prefix)",
    "방송": "broadcast",
    "아직": "still, not yet",
    "이거": "this thing (casual)",
    "점": "point, dot; store (suffix, as in 상점)",
    "구": "ward, district; nine (Sino-Korean number)",
    "는다": "does (plain present verb ending)",
    "러": "in order to (purpose ending, after motion verbs)",
    "별": "star; separate, special (prefix)",
    "용": "for use (suffix, as in 가정용); dragon (ambiguous)",
    "참여": "participation",
    "활동": "activity",
    "나라": "country",
    "단": "group, organization (suffix); simply, just",
    "몇": "how many, several",
    "방법": "method, way",
    "사회": "society",
    "소": "cow; small (prefix, as in 소규모)",
    "란": "column, section (as in 광고란); quoting particle (short for 이란)",
    "어디": "where",
    "위한": "for, for the sake of (modifier of 위하다)",
    "정보": "information",
    "중요": "importance, important",
    "만나": "stem of 만나다 (to meet)",
    "보내": "stem of 보내다 (to send)",
    "이후": "afterwards, since",
    "정부": "government",
    "진행": "progress, proceeding",
    "최고": "the best",
    "통해": "through, via (from 통하다)",
    "긴": "long (modifier of 길다)",
    "법": "law; method (suffix, as in 방법)",
    "싫": "stem of 싫다 (to dislike)",
    "작": "stem of 작다 (to be small); work (suffix, as in 작품)",
    "준비": "preparation",
    "중국": "China",
    "총": "gun; total (prefix, as in 총액)",
    "그것": "that thing",
    "근데": "by the way, but (casual, short for 그런데)",
    "돼": "becomes, is okay (casual/contracted form of 되다)",
    "드": "part of an emphatic/list-forming grammar pattern (e.g. ~든지); no independent meaning alone",
    "든": "or, whether (particle, as in 이든 저든)",
    "새": "new (prefix); bird",
    "어야": "must (obligation connective ending)",
    "이러": "stem of 이러다 (to do this, to act this way)",
    "재": "ash; again (prefix, as in 재사용 = reuse)",
    "천": "thousand",
    "확인": "confirmation, checking",
    "까": "shall we? (casual question ending, short for 까요)",
    "방": "room",
    "시키": "stem of 시키다 (to make someone do, to order)",
    "인간": "human being",
    "제작": "production, making",
    "테": "frame, rim; loanword fragment (as in 카세트 = cassette)",
    "해도": "even if (one) does (connective of 하다)",
    "가족": "family",
    "계": "system, field (suffix, as in 경제계); plan (short for 계획)",
    "계획": "plan",
    "교육": "education",
    "국가": "nation, country",
    "대통령": "president",
    "리": "mile-like distance unit; reason, principle (suffix, as in 이치); village unit",
    "문": "door",
    "문화": "culture",
    "배": "stomach; boat; pear; times (multiplier, as in 두 배 = twice)",
    "약": "medicine; about, approximately",
    "연구": "research",
    "인지": "whether (indirect question particle); cognition (noun, ambiguous)",
    "트": "loanword fragment (e.g. 아파트 = apartment); no independent meaning alone",
    "결과": "result",
    "다니": "attends, goes regularly (from 다니다); I see that... (exclamatory ending, ambiguous)",
    "도시": "city",
    "려고": "in order to, intending to (purpose connective)",
    "바": "the thing, the way (formal dependent noun, as in 아는 바)",
    "사건": "incident, case",
    "상태": "state, condition",
    "조금": "a little",
    "참": "truly, really",
    "결정": "decision",
    "경기": "match, game; economy (short for 경기 both spellings, ambiguous)",
    "관련": "relation, connection",
    "그래서": "so, therefore",
    "그러나": "however, but",
    "둘": "two (native Korean number)",
    "모습": "appearance, figure",
    "없이": "without",
    "초": "second (time unit); candle",
    "피": "blood",
    "관계": "relationship",
    "듣": "stem of 듣다 (to listen, to hear)",
    "라면": "instant noodles; if (particle, ambiguous)",
    "막": "just now, right (adverb); membrane, curtain (ambiguous)",
    "무슨": "what kind of",
    "반": "half; class (as in 학급의 반) (ambiguous)",
    "보여": "shows, is shown (casual form of 보이다)",
    "사이": "between, gap",
    "생": "life, raw (prefix, as in 생일 = life-day = birthday)",
    "아들": "son",
    "얻": "stem of 얻다 (to obtain, to get)",
    "이용": "use, utilization",
    "힘": "strength, power",
    "나오": "stem of 나오다 (to come out)",
    "노래": "song",
    "누구": "who",
    "몸": "body",
    "상황": "situation",
    "십": "ten (Sino-Korean number)",
    "포함": "inclusion",
    "프로그램": "program",
    "글": "writing, text",
    "기술": "technology, skill",
    "뜻": "meaning",
    "마지막": "the last, final",
    "머리": "head, hair",
    "이것": "this thing",
    "읽": "stem of 읽다 (to read)",
    "갖": "stem of 갖다 (to have, contraction of 가지다)",
    "공개": "disclosure, public release",
    "기록": "record",
    "부분": "part, portion",
    "안녕": "hello, peace (as in 안녕하세요)",
    "위치": "location",
    "의미": "meaning",
    "이미": "already",
    "전화": "phone",
    "지원": "support; application (for a job, ambiguous)",
    "질": "quality (suffix); illness (ambiguous)",
    "께": "to (honorific particle)",
    "대학": "university",
    "물론": "of course",
    "여러": "several, various",
    "개발": "development",
    "괜찮": "stem of 괜찮다 (to be okay)",
    "그녀": "she",
    "드리": "stem of 드리다 (to give, humble form)",
    "러시아": "Russia",
    "발견": "discovery",
    "새로운": "new (modifier of 새롭다)",
    "은데": "but, and (background connective, after consonant)",
    "하루": "one day",
    "그럼": "then, in that case",
    "아무": "any, anyone",
    "언제": "when",
    "올": "to come (future/modifier form of 오다)",
    "인가": "is it? (casual question ending); authorization (noun, ambiguous)",
    "자리": "seat, position",
    "기억": "memory",
    "넣": "stem of 넣다 (to put in)",
    "높": "stem of 높다 (to be high)",
    "듯": "as if, seeming (as in 그런 듯하다)",
    "무": "nothing (prefix, as in 무료 = free); radish (ambiguous)",
    "발표": "presentation, announcement",
    "얘기": "talk, story (casual form of 이야기)",
    "엄마": "mom",
    "여러분": "everyone (formal address)",
    "역사": "history",
    "운동": "exercise, movement",
    "이랑": "and, with (casual particle)",
    "이해": "understanding",
    "출장": "business trip",
    "한다고": "says that (one) does (quoting form of 한다)",
    "가격": "price",
    "갈": "to go (future/modifier form of 가다)",
    "꼭": "definitely, surely",
    "만큼": "as much as (particle)",
    "시대": "era, period",
    "아버지": "father",
    "양": "amount, quantity (suffix); sheep (ambiguous)",
    "김": "seaweed; steam (ambiguous, also a common surname)",
    "넘": "stem of 넘다 (to exceed, to cross over)",
    "믿": "stem of 믿다 (to believe)",
    "삼": "three (Sino-Korean number); ginseng (ambiguous)",
    "아닌": "not being (modifier of 아니다)",
    "역시": "also, as expected",
    "편": "side, part; convenience (suffix, ambiguous)",
    "행복": "happiness",
    "회사": "company",
    "국민": "citizen, people (of a nation)",
    "기준": "standard, criterion",
    "꿈": "dream",
    "마다": "every, each (particle)",
    "부산": "Busan",
    "인터넷": "internet",
    "책": "book",
    "항상": "always",
    "각": "each",
    "거리": "street, distance",
    "거의": "almost",
    "경제": "economy",
    "기분": "mood, feeling",
    "대상": "target, subject",
    "먼저": "first",
    "배우": "stem of 배우다 (to learn); actor (noun, ambiguous)",
    "아침": "morning, breakfast",
    "얼굴": "face",
    "운영": "operation, management",
    "존재": "existence",
    "코": "nose",
    "판매": "sales",
    "내용": "content, substance",
  };
})();
