// HanaPath Sentence Examination Eligibility — Shard A (rows s0001–s1050).
// Plain static browser global — no build step. One of four deterministic,
// non-overlapping shards; the public aggregate is published by
// sentence_exam_eligibility.js after all four shards load.
(function () {
  "use strict";
  var registry = (window.HANAPATH_SENTENCE_EXAM_ELIGIBILITY_SHARDS =
    window.HANAPATH_SENTENCE_EXAM_ELIGIBILITY_SHARDS || {});
  registry.A = {
    shardId: "A",
    firstOrder: 1,
    lastOrder: 1050,
    reviewedRows: {
      s0001: {
        typedClass: "canonical",
        examPromptEn: "As for Hangul, say that it is fun to a classmate.",
        canonicalTargetKey: "한글은 재미있어요.",
        acceptedAnswers: ["한글은 재미있어요."],
        eligibleModes: ["translate-type", "sentence-recognition"],
        primaryCompetencies: ["topic-neun", "present-polite"],
        supportingLessonIds: ["sn1-firstwords-u1-l1"],
        minimumSectionOrder: 1,
        exclusionReasons: [],
        reviewStatus: "approved",
        reviewedAt: "2026-07-21T00:00:00Z",
        reviewerNote: "Worked example from spec §5.1"
      },
      s0002: {
        typedClass: "canonical",
        examPromptEn: "As for me, say that I study Korean.",
        canonicalTargetKey: "저는 한국어를 공부해요.",
        acceptedAnswers: ["저는 한국어를 공부해요."],
        eligibleModes: ["translate-type", "sentence-recognition"],
        primaryCompetencies: ["topic-neun", "object-eul-reul", "present-polite"],
        supportingLessonIds: ["sn1-firstwords-u1-l2"],
        minimumSectionOrder: 1,
        exclusionReasons: [],
        reviewStatus: "approved",
        reviewedAt: "2026-07-21T00:00:00Z",
        reviewerNote: "Worked example"
      },
      s0003: {
        typedClass: "canonical",
        examPromptEn: "Say that speech is fast.",
        canonicalTargetKey: "말이 빨라요.",
        acceptedAnswers: ["말이 빨라요."],
        eligibleModes: ["translate-type", "sentence-recognition"],
        primaryCompetencies: ["subject-i-ga", "present-polite"],
        supportingLessonIds: ["sn1-firstwords-u1-l3"],
        minimumSectionOrder: 1,
        exclusionReasons: [],
        reviewStatus: "approved",
        reviewedAt: "2026-07-21T00:00:00Z",
        reviewerNote: "Worked example"
      },
      s0004: {
        typedClass: "canonical",
        examPromptEn: "As for this word, say that it is easy.",
        canonicalTargetKey: "이 단어는 쉬워요.",
        acceptedAnswers: ["이 단어는 쉬워요."],
        eligibleModes: ["translate-type", "sentence-recognition"],
        primaryCompetencies: ["topic-neun", "present-polite"],
        supportingLessonIds: ["sn1-firstwords-u1-l4"],
        minimumSectionOrder: 1,
        exclusionReasons: [],
        reviewStatus: "approved",
        reviewedAt: "2026-07-21T00:00:00Z",
        reviewerNote: "Worked example"
      },
      s0005: {
        typedClass: "canonical",
        examPromptEn: "Say that I listen to the sound.",
        canonicalTargetKey: "소리를 들어요.",
        acceptedAnswers: ["소리를 들어요."],
        eligibleModes: ["translate-type", "sentence-recognition"],
        primaryCompetencies: ["object-eul-reul", "present-polite"],
        supportingLessonIds: ["sn1-firstwords-u1-l5"],
        minimumSectionOrder: 1,
        exclusionReasons: [],
        reviewStatus: "approved",
        reviewedAt: "2026-07-21T00:00:00Z",
        reviewerNote: "Worked example"
      },
      s0006: {
        typedClass: "canonical",
        examPromptEn: "Say that I read a book.",
        canonicalTargetKey: "책을 읽어요.",
        acceptedAnswers: ["책을 읽어요."],
        eligibleModes: ["translate-type", "sentence-recognition"],
        primaryCompetencies: ["object-eul-reul", "present-polite"],
        supportingLessonIds: ["sn1-firstwords-u1-l6"],
        minimumSectionOrder: 1,
        exclusionReasons: [],
        reviewStatus: "approved",
        reviewedAt: "2026-07-21T00:00:00Z",
        reviewerNote: "Worked example"
      },
      s0007: {
        typedClass: "canonical",
        examPromptEn: "Say that I listen to music.",
        canonicalTargetKey: "음악을 들어요.",
        acceptedAnswers: ["음악을 들어요."],
        eligibleModes: ["translate-type", "sentence-recognition"],
        primaryCompetencies: ["object-eul-reul", "present-polite"],
        supportingLessonIds: ["sn1-firstwords-u1-l7"],
        minimumSectionOrder: 1,
        exclusionReasons: [],
        reviewStatus: "approved",
        reviewedAt: "2026-07-21T00:00:00Z",
        reviewerNote: "Worked example"
      },
      s0008: {
        typedClass: "canonical",
        examPromptEn: "Say that I write a name.",
        canonicalTargetKey: "이름을 써요.",
        acceptedAnswers: ["이름을 써요."],
        eligibleModes: ["translate-type", "sentence-recognition"],
        primaryCompetencies: ["object-eul-reul", "present-polite"],
        supportingLessonIds: ["sn1-firstwords-u1-l8"],
        minimumSectionOrder: 1,
        exclusionReasons: [],
        reviewStatus: "approved",
        reviewedAt: "2026-07-21T00:00:00Z",
        reviewerNote: "Worked example"
      },
      s0009: {
        typedClass: "canonical",
        examPromptEn: "Say that I read a sentence.",
        canonicalTargetKey: "문장을 읽어요.",
        acceptedAnswers: ["문장을 읽어요."],
        eligibleModes: ["translate-type", "sentence-recognition"],
        primaryCompetencies: ["object-eul-reul", "present-polite"],
        supportingLessonIds: ["sn1-firstwords-u1-l9"],
        minimumSectionOrder: 1,
        exclusionReasons: [],
        reviewStatus: "approved",
        reviewedAt: "2026-07-21T00:00:00Z",
        reviewerNote: "Worked example"
      },
      s0010: {
        typedClass: "canonical",
        examPromptEn: "Say that practice is needed.",
        canonicalTargetKey: "연습이 필요해요.",
        acceptedAnswers: ["연습이 필요해요."],
        eligibleModes: ["translate-type", "sentence-recognition"],
        primaryCompetencies: ["subject-i-ga", "present-polite"],
        supportingLessonIds: ["sn1-firstwords-u1-l10"],
        minimumSectionOrder: 1,
        exclusionReasons: [],
        reviewStatus: "approved",
        reviewedAt: "2026-07-21T00:00:00Z",
        reviewerNote: "Worked example"
      },
      s0011: {
        typedClass: "canonical",
        examPromptEn: "Say hello and that as for me, I am a student.",
        canonicalTargetKey: "안녕하세요. 저는 학생이에요.",
        acceptedAnswers: ["안녕하세요. 저는 학생이에요."],
        eligibleModes: ["translate-type", "sentence-recognition"],
        primaryCompetencies: ["topic-neun", "copula-ieyo", "honorific-si"],
        supportingLessonIds: ["sn1-firstwords-u2-l1"],
        minimumSectionOrder: 1,
        exclusionReasons: [],
        reviewStatus: "approved",
        reviewedAt: "2026-07-21T00:00:00Z",
        reviewerNote: "Worked example"
      },
      s0012: {
        typedClass: "canonical",
        examPromptEn: "Say thank you very much in polite formal style.",
        canonicalTargetKey: "정말 감사합니다.",
        acceptedAnswers: ["정말 감사합니다."],
        eligibleModes: ["translate-type", "sentence-recognition"],
        primaryCompetencies: ["formal-nida"],
        supportingLessonIds: ["sn1-firstwords-u2-l2"],
        minimumSectionOrder: 1,
        exclusionReasons: [],
        reviewStatus: "approved",
        reviewedAt: "2026-07-21T00:00:00Z",
        reviewerNote: "Worked example"
      },
      s0013: {
        typedClass: "canonical",
        examPromptEn: "Say yes, that is right.",
        canonicalTargetKey: "네, 맞아요.",
        acceptedAnswers: ["네, 맞아요."],
        eligibleModes: ["translate-type", "sentence-recognition"],
        primaryCompetencies: ["present-polite"],
        supportingLessonIds: ["sn1-firstwords-u2-l3"],
        minimumSectionOrder: 1,
        exclusionReasons: [],
        reviewStatus: "approved",
        reviewedAt: "2026-07-21T00:00:00Z",
        reviewerNote: "Worked example"
      },
      s0014: {
        typedClass: "canonical",
        examPromptEn: "Say no, it is okay.",
        canonicalTargetKey: "아니요, 괜찮아요.",
        acceptedAnswers: ["아니요, 괜찮아요."],
        eligibleModes: ["translate-type", "sentence-recognition"],
        primaryCompetencies: ["present-polite"],
        supportingLessonIds: ["sn1-firstwords-u2-l4"],
        minimumSectionOrder: 1,
        exclusionReasons: [],
        reviewStatus: "approved",
        reviewedAt: "2026-07-21T00:00:00Z",
        reviewerNote: "Worked example"
      },
      s0015: {
        typedClass: "canonical",
        examPromptEn: "Please give me water.",
        canonicalTargetKey: "물 주세요.",
        acceptedAnswers: ["물 주세요."],
        eligibleModes: ["translate-type", "sentence-recognition"],
        primaryCompetencies: ["imperative-seyo", "honorific-si"],
        supportingLessonIds: ["sn1-firstwords-u2-l5"],
        minimumSectionOrder: 1,
        exclusionReasons: [],
        reviewStatus: "approved",
        reviewedAt: "2026-07-21T00:00:00Z",
        reviewerNote: "Worked example"
      },
      s0016: {
        typedClass: "canonical",
        examPromptEn: "Say sorry for being late in polite formal style.",
        canonicalTargetKey: "늦어서 죄송합니다.",
        acceptedAnswers: ["늦어서 죄송합니다."],
        eligibleModes: ["translate-type", "sentence-recognition"],
        primaryCompetencies: ["formal-nida", "because-aseo"],
        supportingLessonIds: ["sn3-grammar-u1-l1"],
        minimumSectionOrder: 3,
        exclusionReasons: [],
        reviewStatus: "approved",
        reviewedAt: "2026-07-21T00:00:00Z",
        reviewerNote: "Worked example"
      },
      s0017: {
        typedClass: "canonical",
        examPromptEn: "Say it is okay and please do not worry.",
        canonicalTargetKey: "괜찮아요. 걱정하지 마세요.",
        acceptedAnswers: ["괜찮아요. 걱정하지 마세요."],
        eligibleModes: ["translate-type", "sentence-recognition"],
        primaryCompetencies: ["present-polite", "imperative-seyo", "honorific-si"],
        supportingLessonIds: ["sn1-firstwords-u2-l6"],
        minimumSectionOrder: 1,
        exclusionReasons: [],
        reviewStatus: "approved",
        reviewedAt: "2026-07-21T00:00:00Z",
        reviewerNote: "Worked example"
      },
      s0018: {
        typedClass: "canonical",
        examPromptEn: "Please help me.",
        canonicalTargetKey: "저 좀 도와주세요.",
        acceptedAnswers: ["저 좀 도와주세요."],
        eligibleModes: ["translate-type", "sentence-recognition"],
        primaryCompetencies: ["imperative-seyo", "honorific-si"],
        supportingLessonIds: ["sn1-firstwords-u2-l7"],
        minimumSectionOrder: 1,
        exclusionReasons: [],
        reviewStatus: "approved",
        reviewedAt: "2026-07-21T00:00:00Z",
        reviewerNote: "Worked example"
      },
      s0019: {
        typedClass: "canonical",
        examPromptEn: "Say just a moment, I will come right back.",
        canonicalTargetKey: "잠시만요. 금방 올게요.",
        acceptedAnswers: ["잠시만요. 금방 올게요."],
        eligibleModes: ["translate-type", "sentence-recognition"],
        primaryCompetencies: ["present-polite", "future-geoyeyo"],
        supportingLessonIds: ["sn1-firstwords-u2-l8"],
        minimumSectionOrder: 1,
        exclusionReasons: [],
        reviewStatus: "approved",
        reviewedAt: "2026-07-21T00:00:00Z",
        reviewerNote: "Worked example"
      },
      s0020: {
        typedClass: "canonical",
        examPromptEn: "As for me, say that I do not know well.",
        canonicalTargetKey: "저는 잘 몰라요.",
        acceptedAnswers: ["저는 잘 몰라요."],
        eligibleModes: ["translate-type", "sentence-recognition"],
        primaryCompetencies: ["topic-neun", "present-polite"],
        supportingLessonIds: ["sn1-firstwords-u2-l9"],
        minimumSectionOrder: 1,
        exclusionReasons: [],
        reviewStatus: "approved",
        reviewedAt: "2026-07-21T00:00:00Z",
        reviewerNote: "Worked example"
      }
    }
  };
})();
