window.VOCAB_BROWSE_NOTES = {
  "이": {
    meaning: "subject particle",
    partOfSpeech: "particle",
    exampleKo: "책이 있어요.",
    examplePronunciation: "chaegi isseoyo",
    exampleEn: "There is a book.",
    formNote: "이/가 selection depends on batchim: use 이 after a noun ending in a consonant sound.",
  },
  "가": {
    meaning: "subject particle",
    partOfSpeech: "particle",
    exampleKo: "친구가 와요.",
    examplePronunciation: "chinguga wayo",
    exampleEn: "A friend is coming.",
    formNote: "이/가 selection depends on batchim: use 가 after a noun ending in a vowel sound.",
  },
  "은": {
    meaning: "topic particle",
    partOfSpeech: "particle",
    exampleKo: "책은 여기 있어요.",
    examplePronunciation: "chaekeun yeogi isseoyo",
    exampleEn: "The book is here.",
    formNote: "은/는 selection depends on batchim: use 은 after a noun ending in a consonant sound.",
  },
  "는": {
    meaning: "topic particle",
    partOfSpeech: "particle",
    exampleKo: "저는 학생이에요.",
    examplePronunciation: "jeoneun haksaengieyo",
    exampleEn: "I am a student.",
    formNote: "은/는 selection depends on batchim: use 는 after a noun ending in a vowel sound.",
  },
  "을": {
    meaning: "object particle",
    partOfSpeech: "particle",
    exampleKo: "책을 읽어요.",
    examplePronunciation: "chaegeul ilgeoyo",
    exampleEn: "I read a book.",
    formNote: "을/를 selection depends on batchim: use 을 after a noun ending in a consonant sound.",
  },
  "를": {
    meaning: "object particle",
    partOfSpeech: "particle",
    exampleKo: "사과를 먹어요.",
    examplePronunciation: "sagwareul meogeoyo",
    exampleEn: "I eat an apple.",
    formNote: "을/를 selection depends on batchim: use 를 after a noun ending in a vowel sound.",
  },
  "과": {
    meaning: "and / with",
    partOfSpeech: "particle",
    exampleKo: "밥과 물을 먹어요.",
    examplePronunciation: "bapgwa mureul meogeoyo",
    exampleEn: "I eat rice and drink water.",
    formNote: "과/와 selection depends on batchim: use 과 after a noun ending in a consonant sound.",
  },
  "와": {
    meaning: "and / with",
    partOfSpeech: "particle",
    exampleKo: "친구와 같이 가요.",
    examplePronunciation: "chinguwa gachi gayo",
    exampleEn: "I go together with a friend.",
    formNote: "과/와 selection depends on batchim: use 와 after a noun ending in a vowel sound.",
  },
  "의": {
    meaning: "possessive particle",
    partOfSpeech: "particle",
    exampleKo: "저의 책이에요.",
    examplePronunciation: "jeoe chaegieyo",
    exampleEn: "It is my book.",
    formNote: "의 marks possession. In everyday speech it is often pronounced 에.",
    soundNote: "The possessive 의 often softens to 에 in casual speech.",
  },
  "보다": {
    meaning: "to see, to watch",
    partOfSpeech: "verb",
    exampleKo: "영화를 봐요.",
    examplePronunciation: "yeonghwareul bwayo",
    exampleEn: "I watch a movie.",
    formNote: "보다 is the dictionary form. In this sentence it becomes 봐요 because 보 + 아요 contracts to 봐요.",
  },
};

window.VOCAB_BROWSE_EXTRAS = [
  {
    rank: 5001,
    korean: "가다",
    meaning: "to go",
    partOfSpeech: "verb",
    englishSpelling: "gada",
    romanization: "gada",
    pronunciation: "gada",
    frequencyBand: "1-500",
    syllables: 2,
    exampleKo: "지금 가요.",
    examplePronunciation: "jigeum gayo",
    exampleEn: "I'm going now.",
    formNote: "가다 is the dictionary form. In this sentence it becomes 가요 because polite present uses the stem 가 plus -요.",
  },
  {
    rank: 5002,
    korean: "오다",
    meaning: "to come",
    partOfSpeech: "verb",
    englishSpelling: "oda",
    romanization: "oda",
    pronunciation: "oda",
    frequencyBand: "1-500",
    syllables: 2,
    exampleKo: "친구가 와요.",
    examplePronunciation: "chinguga wayo",
    exampleEn: "A friend is coming.",
    formNote: "오다 is the dictionary form. In this sentence it becomes 와요 because 오 + 아요 contracts to 와요.",
  },
  {
    rank: 5003,
    korean: "하다",
    meaning: "to do",
    partOfSpeech: "verb",
    englishSpelling: "hada",
    romanization: "hada",
    pronunciation: "hada",
    frequencyBand: "1-500",
    syllables: 2,
    exampleKo: "뭐 해요?",
    examplePronunciation: "mwo haeyo",
    exampleEn: "What are you doing?",
    formNote: "하다 is the dictionary form. In this sentence it becomes 해요, the normal polite present form of 하다.",
  },
  {
    rank: 5004,
    korean: "먹다",
    meaning: "to eat",
    partOfSpeech: "verb",
    englishSpelling: "meokda",
    romanization: "meokda",
    pronunciation: "meokda",
    frequencyBand: "1-500",
    syllables: 2,
    exampleKo: "뭐 먹어요?",
    examplePronunciation: "mwo meogeoyo",
    exampleEn: "What are you eating?",
    formNote: "먹다 is the dictionary form. In this sentence it becomes 먹어요 by adding the polite present ending -어요.",
  },
  {
    rank: 5005,
    korean: "마시다",
    meaning: "to drink",
    partOfSpeech: "verb",
    englishSpelling: "masida",
    romanization: "masida",
    pronunciation: "masida",
    frequencyBand: "1-500",
    syllables: 3,
    exampleKo: "물을 마셔요.",
    examplePronunciation: "mureul masyeoyo",
    exampleEn: "I drink water.",
    formNote: "마시다 is the dictionary form. In this sentence it becomes 마셔요 because 시 + 어요 contracts to 셔요.",
  },
  {
    rank: 5006,
    korean: "읽다",
    meaning: "to read",
    partOfSpeech: "verb",
    englishSpelling: "ikda",
    romanization: "ikda",
    pronunciation: "ikda",
    frequencyBand: "1-500",
    syllables: 2,
    exampleKo: "책을 읽어요.",
    examplePronunciation: "chaegeul ilgeoyo",
    exampleEn: "I read a book.",
    formNote: "읽다 is the dictionary form. In this sentence it becomes 읽어요 by adding -어요. The final ㄺ is pronounced like ㄱ in this form.",
  },
  {
    rank: 5007,
    korean: "듣다",
    meaning: "to listen, to hear",
    partOfSpeech: "verb",
    englishSpelling: "deutda",
    romanization: "deutda",
    pronunciation: "deutda",
    frequencyBand: "1-500",
    syllables: 2,
    exampleKo: "음악을 들어요.",
    examplePronunciation: "eumageul deureoyo",
    exampleEn: "I listen to music.",
    formNote: "듣다 is the dictionary form. In this sentence it becomes 들어요 because ㄷ irregular verbs change ㄷ to ㄹ before a vowel ending: 듣 + 어요 -> 들어요.",
    soundNote: "음악을 links in speech: 음악을 -> 으마글, so the example sounds closer to eu-ma-geul deu-reo-yo.",
  },
  {
    rank: 5008,
    korean: "걷다",
    meaning: "to walk",
    partOfSpeech: "verb",
    englishSpelling: "geotda",
    romanization: "geotda",
    pronunciation: "geotda",
    frequencyBand: "1-500",
    syllables: 2,
    exampleKo: "매일 걸어요.",
    examplePronunciation: "maeil georeoyo",
    exampleEn: "I walk every day.",
    formNote: "걷다 is the dictionary form. In this sentence it becomes 걸어요 because ㄷ irregular verbs change ㄷ to ㄹ before a vowel ending: 걷 + 어요 -> 걸어요.",
  },
  {
    rank: 5009,
    korean: "돕다",
    meaning: "to help",
    partOfSpeech: "verb",
    englishSpelling: "dopda",
    romanization: "dopda",
    pronunciation: "dopda",
    frequencyBand: "1-500",
    syllables: 2,
    exampleKo: "친구를 도와요.",
    examplePronunciation: "chingureul dowayo",
    exampleEn: "I help a friend.",
    formNote: "돕다 is the dictionary form. In this sentence it becomes 도와요 because ㅂ irregular verbs change ㅂ to 우 before a vowel ending: 돕 + 아요 -> 도와요.",
  },
  {
    rank: 5010,
    korean: "모르다",
    meaning: "to not know",
    partOfSpeech: "verb",
    englishSpelling: "moreuda",
    romanization: "moreuda",
    pronunciation: "moreuda",
    frequencyBand: "1-500",
    syllables: 3,
    exampleKo: "저는 몰라요.",
    examplePronunciation: "jeoneun mollayo",
    exampleEn: "I don't know.",
    formNote: "모르다 is the dictionary form. In this sentence it becomes 몰라요 because 르 irregular verbs add ㄹ and shift the vowel: 모르 + 아요 -> 몰라요.",
  },
  {
    rank: 5011,
    korean: "짓다",
    meaning: "to build / make",
    partOfSpeech: "verb",
    englishSpelling: "jitda",
    romanization: "jitda",
    pronunciation: "jitda",
    frequencyBand: "1-500",
    syllables: 2,
    exampleKo: "집을 지어요.",
    examplePronunciation: "jibeul jieoyo",
    exampleEn: "I build a house.",
    formNote: "짓다 is the dictionary form. In this sentence it becomes 지어요 because ㅅ irregular verbs drop ㅅ before a vowel ending: 짓 + 어요 -> 지어요.",
  },
  {
    rank: 5012,
    korean: "쓰다",
    meaning: "to write / use",
    partOfSpeech: "verb",
    englishSpelling: "sseuda",
    romanization: "sseuda",
    pronunciation: "sseuda",
    frequencyBand: "1-500",
    syllables: 2,
    exampleKo: "이름을 써요.",
    examplePronunciation: "ireumeul sseoyo",
    exampleEn: "I write my name.",
    formNote: "쓰다 is the dictionary form. In this sentence it becomes 써요 because the ㅡ vowel drops before -어요.",
  },
  {
    rank: 5013,
    korean: "배우다",
    meaning: "to learn",
    partOfSpeech: "verb",
    englishSpelling: "baeuda",
    romanization: "baeuda",
    pronunciation: "baeuda",
    frequencyBand: "1-500",
    syllables: 3,
    exampleKo: "저는 한국어를 배워요.",
    examplePronunciation: "jeoneun hangugeoreul baewoyo",
    exampleEn: "I learn Korean.",
    formNote: "배우다 is the dictionary form. In this sentence it becomes 배워요 because 배우 + 어요 contracts to 배워요.",
  },
];
