// HanaPath word lesson plan (Words section curriculum).
// Plain static browser global — no modules, no build step. Loaded before app.js.
// Every newWordIds entry must exist in words_curated_core.js
// (verified by scripts/audit-words-data.mjs).
(function () {
  "use strict";

  var DEFAULT_CHECKPOINTS = ["ko-to-meaning", "audio-to-meaning", "meaning-to-ko", "type-ko", "sentence-blank"];
  var DEFAULT_PASS = { minFirstTryPct: 75, requireTypedAttempt: true };

  var previousId = null;
  function defineLesson(lesson) {
    var full = {
      id: lesson.id,
      stage: lesson.stage,
      title: lesson.title,
      subtitle: lesson.subtitle,
      goal: lesson.goal,
      tutorial: Boolean(lesson.tutorial),
      unlock: {
        requiresAlphabetComplete: true,
        previousLessonId: previousId,
      },
      newWordIds: lesson.newWordIds,
      reviewPolicy: { includeDue: true, maxReviewCards: 4 },
      checkpoints: lesson.checkpoints || DEFAULT_CHECKPOINTS,
      pass: lesson.pass || DEFAULT_PASS,
    };
    previousId = lesson.id;
    return full;
  }

  window.HANAPATH_WORD_LESSONS = [
    defineLesson({
      id: "w0-post-hangul-bridge-01",
      stage: "W0",
      title: "Post-Hangul bridge",
      subtitle: "Turn letters into words",
      goal: "Learn how word cards work: see, hear, type, repeat, and review.",
      tutorial: true,
      newWordIds: ["w0001_hangul", "w0002_hangugeo", "w0003_mal", "w0004_daneo", "w0005_sori"],
    }),
    defineLesson({
      id: "w0-post-hangul-bridge-02",
      stage: "W0",
      title: "Read, listen, write",
      subtitle: "The study verbs",
      goal: "Learn the verbs you will use to talk about learning Korean.",
      newWordIds: ["w0006_ikda", "w0007_deutda", "w0008_sseuda", "w0009_munjang", "w0010_yeonseup"],
    }),
    defineLesson({
      id: "w1-survival-core-01",
      stage: "W1",
      title: "Survival core",
      subtitle: "Words you can use immediately",
      goal: "Understand, hear, type, and say 5 survival words.",
      newWordIds: ["w0101_annyeonghaseyo", "w0102_gamsahamnida", "w0103_ne", "w0104_aniyo", "w0105_juseyo"],
    }),
    defineLesson({
      id: "w1-survival-core-02",
      stage: "W1",
      title: "Survival core II",
      subtitle: "Polite problem-solving",
      goal: "Apologise, ask for help, and buy yourself a moment.",
      newWordIds: ["w0106_joesonghamnida", "w0107_gwaenchanayo", "w0108_dowajuseyo", "w0109_jamsimanyo", "w0110_mollayo", "w0111_algesseoyo"],
    }),
    defineLesson({
      id: "w2-people-pronouns-01",
      stage: "W2",
      title: "People and pronouns",
      subtitle: "Talking about people",
      goal: "Introduce yourself and ask who someone is.",
      newWordIds: ["w0201_jeo_i", "w0205_saram", "w0206_chingu", "w0209_ireum", "w0210_nugu"],
    }),
    defineLesson({
      id: "w2-people-pronouns-02",
      stage: "W2",
      title: "People and pronouns II",
      subtitle: "We, you, and roles",
      goal: "Learn casual pronouns and the people around you.",
      newWordIds: ["w0202_na", "w0203_neo", "w0204_uri", "w0207_haksaeng", "w0208_seonsaengnim"],
    }),
    defineLesson({
      id: "w3-things-demonstratives-01",
      stage: "W3",
      title: "Things and demonstratives",
      subtitle: "This one, that one",
      goal: "Point at things and ask what they are.",
      newWordIds: ["w0304_igeo", "w0305_geugeo", "w0306_jeogeo", "w0307_geot", "w0308_mwo"],
    }),
    defineLesson({
      id: "w3-things-demonstratives-02",
      stage: "W3",
      title: "Things and demonstratives II",
      subtitle: "This book, that person",
      goal: "Use this/that before nouns you already know.",
      newWordIds: ["w0301_i_this", "w0302_geu_that", "w0303_jeo_that_over", "w0309_chaek", "w0310_jeonhwa"],
    }),
    defineLesson({
      id: "w4-places-movement-01",
      stage: "W4",
      title: "Places and movement",
      subtitle: "Here, there, home",
      goal: "Name the places around you.",
      newWordIds: ["w0401_yeogi", "w0402_geogi", "w0403_jeogi", "w0404_jip", "w0405_hakgyo"],
    }),
    defineLesson({
      id: "w4-places-movement-02",
      stage: "W4",
      title: "Places and movement II",
      subtitle: "Going and coming",
      goal: "Find the bathroom, find the station, go and come.",
      newWordIds: ["w0406_hoesa", "w0407_hwajangsil", "w0408_yeok", "w0409_gada", "w0410_oda"],
    }),
    defineLesson({
      id: "w5-food-drink-01",
      stage: "W5",
      title: "Food and drink",
      subtitle: "Eating essentials",
      goal: "Order water, talk about meals, eat and drink.",
      newWordIds: ["w0501_mul", "w0502_bap", "w0503_eumsik", "w0509_meokda", "w0510_masida"],
    }),
    defineLesson({
      id: "w5-food-drink-02",
      stage: "W5",
      title: "Food and drink II",
      subtitle: "At the café and market",
      goal: "Name common foods and drinks.",
      newWordIds: ["w0504_keopi", "w0505_cha", "w0506_gogi", "w0507_gwail", "w0508_ppang"],
    }),
    defineLesson({
      id: "w6-time-daily-01",
      stage: "W6",
      title: "Time and daily rhythm",
      subtitle: "Yesterday, today, tomorrow",
      goal: "Anchor events in time.",
      newWordIds: ["w0601_oneul", "w0602_naeil", "w0603_eoje", "w0604_jigeum", "w0610_eonje"],
    }),
    defineLesson({
      id: "w6-time-daily-02",
      stage: "W6",
      title: "Time and daily rhythm II",
      subtitle: "Morning to evening",
      goal: "Talk about the parts of the day.",
      newWordIds: ["w0605_sigan", "w0606_achim", "w0607_jeomsim", "w0608_jeonyeok", "w0609_nal"],
    }),
    defineLesson({
      id: "w7-core-actions-01",
      stage: "W7",
      title: "Core actions",
      subtitle: "Do, have, see, speak",
      goal: "Learn the verbs Korean sentences are built on.",
      newWordIds: ["w0701_hada", "w0702_itda", "w0703_eopda", "w0704_boda", "w0705_malhada"],
    }),
    defineLesson({
      id: "w7-core-actions-02",
      stage: "W7",
      title: "Core actions II",
      subtitle: "Daily-life verbs",
      goal: "Buy, meet, sleep, get up, and like.",
      newWordIds: ["w0706_sada", "w0707_mannada", "w0708_jada", "w0709_ireonada", "w0710_joahada"],
    }),
    defineLesson({
      id: "w8-feelings-descriptions-01",
      stage: "W8",
      title: "Feelings and descriptions",
      subtitle: "Good, bad, big, small",
      goal: "Describe things and say what you like.",
      newWordIds: ["w0801_jota", "w0802_silta", "w0803_keuda", "w0804_jakda", "w0809_masitda"],
    }),
    defineLesson({
      id: "w8-feelings-descriptions-02",
      stage: "W8",
      title: "Feelings and descriptions II",
      subtitle: "Many, few, fun, tired",
      goal: "Describe amounts and how you feel.",
      newWordIds: ["w0805_manta", "w0806_jeokda", "w0807_jaemiitda", "w0808_pigonhada", "w0810_yeppeuda"],
    }),
    defineLesson({
      id: "w9-question-words-01",
      stage: "W9",
      title: "Question words",
      subtitle: "Where, why, how",
      goal: "Ask the questions that get you around.",
      newWordIds: ["w0901_eodi", "w0902_wae", "w0903_eotteoke", "w0904_eolma", "w0905_myeot"],
    }),
    defineLesson({
      id: "w9-question-words-02",
      stage: "W9",
      title: "Question words II",
      subtitle: "Which and what kind",
      goal: "Ask about kinds, choices, and degree.",
      newWordIds: ["w0906_museun", "w0907_eotteon", "w0908_eolmana"],
    }),
    defineLesson({
      id: "w10-function-words-01",
      stage: "W10",
      title: "Function words 1",
      subtitle: "The little words that glue Korean together",
      goal: "Meet the topic, subject, and object markers.",
      newWordIds: ["fw1001_eun_neun", "fw1002_i_ga", "fw1003_eul_reul", "fw1004_e", "fw1006_do"],
      checkpoints: ["ko-to-meaning", "meaning-to-ko", "sentence-blank", "function-usage"],
      pass: { minFirstTryPct: 60, requireTypedAttempt: false },
    }),
    defineLesson({
      id: "w10-function-words-02",
      stage: "W10",
      title: "Function words 1 · part 2",
      subtitle: "Where, with, and and",
      goal: "Mark action locations and join words together.",
      newWordIds: ["fw1005_eseo", "fw1007_ui", "fw1008_wa_gwa", "fw1009_hago", "fw1010_go"],
      checkpoints: ["ko-to-meaning", "meaning-to-ko", "sentence-blank", "function-usage"],
      pass: { minFirstTryPct: 60, requireTypedAttempt: false },
    }),

    defineLesson({
      id: "w11-daily-objects-tech-01",
      stage: "W11",
      title: "Daily objects and technology",
      subtitle: "What's in your bag",
      goal: "Name everyday items you carry and wear.",
      newWordIds: ["w1101_gabang", "w1102_sinbal", "w1103_ot", "w1104_sigye", "w1105_angyeong"],
    }),
    defineLesson({
      id: "w11-daily-objects-tech-02",
      stage: "W11",
      title: "Daily objects and technology II",
      subtitle: "Small essentials",
      goal: "Ask about umbrellas, wallets, and keys.",
      newWordIds: ["w1106_usan", "w1107_jigap", "w1111_yeolsoe", "w1112_jongi", "w1115_gawi"],
    }),
    defineLesson({
      id: "w11-daily-objects-tech-03",
      stage: "W11",
      title: "Daily objects and technology III",
      subtitle: "Screens and devices",
      goal: "Talk about computers, phones, and photos.",
      newWordIds: ["w1108_keompyuteo", "w1109_tellebijeon", "w1110_kamera", "w1118_inteonet", "w1120_sajin"],
    }),
    defineLesson({
      id: "w11-daily-objects-tech-04",
      stage: "W11",
      title: "Daily objects and technology IV",
      subtitle: "Writing and charging",
      goal: "Round out study and tech vocabulary.",
      newWordIds: ["w1113_pen", "w1114_yeonpil", "w1116_baeteori", "w1117_chungjeongi", "w1119_imeil"],
    }),

    defineLesson({
      id: "w12-home-routine-01",
      stage: "W12",
      title: "Home and routine",
      subtitle: "Rooms in the house",
      goal: "Name the rooms and furniture around you.",
      newWordIds: ["w1201_bang", "w1202_chimdae", "w1203_bueok", "w1212_geosil", "w1215_uija"],
    }),
    defineLesson({
      id: "w12-home-routine-02",
      stage: "W12",
      title: "Home and routine II",
      subtitle: "Furniture and fixtures",
      goal: "Name more household objects.",
      newWordIds: ["w1209_otjang", "w1210_changmun", "w1211_mun", "w1213_naengjanggo", "w1216_chaeksang"],
    }),
    defineLesson({
      id: "w12-home-routine-03",
      stage: "W12",
      title: "Home and routine III",
      subtitle: "Your daily habits",
      goal: "Talk about cleaning, washing, and resting at home.",
      newWordIds: ["w1204_cheongsohada", "w1205_ssitda", "w1206_swida", "w1207_yorihada", "w1208_syawohada"],
    }),
    defineLesson({
      id: "w12-home-routine-04",
      stage: "W12",
      title: "Home and routine IV",
      subtitle: "Open, close, on, off",
      goal: "Control the things around your house.",
      newWordIds: ["w1214_siktak", "w1217_yeolda", "w1218_datda", "w1219_kyeoda", "w1220_kkeuda"],
    }),

    defineLesson({
      id: "w13-travel-city-01",
      stage: "W13",
      title: "Travel and city",
      subtitle: "Getting around",
      goal: "Name common ways to travel.",
      newWordIds: ["w1301_gonghang", "w1302_gicha", "w1303_beoseu", "w1304_jihacheol", "w1305_taeksi"],
    }),
    defineLesson({
      id: "w13-travel-city-02",
      stage: "W13",
      title: "Travel and city II",
      subtitle: "Planning a trip",
      goal: "Talk about hotels, tickets, and trips.",
      newWordIds: ["w1306_hotel", "w1307_yeohaeng", "w1308_pyo", "w1311_yeogwon", "w1312_jim"],
    }),
    defineLesson({
      id: "w13-travel-city-03",
      stage: "W13",
      title: "Travel and city III",
      subtitle: "Finding your way",
      goal: "Ask directions and read a map.",
      newWordIds: ["w1309_gil", "w1310_jido", "w1316_gongwon", "w1317_dari", "w1320_geori"],
    }),
    defineLesson({
      id: "w13-travel-city-04",
      stage: "W13",
      title: "Travel and city IV",
      subtitle: "Arriving and departing",
      goal: "Arrive, depart, and book ahead.",
      newWordIds: ["w1313_dochakhada", "w1314_chulbalhada", "w1315_yeyakhada", "w1318_byeong", "w1319_geuncheo"],
    }),

    defineLesson({
      id: "w14-shopping-money-01",
      stage: "W14",
      title: "Shopping and money",
      subtitle: "Paying for things",
      goal: "Talk about money, price, and payment.",
      newWordIds: ["w1401_don", "w1402_gagyeok", "w1403_kadeu", "w1404_hyeongeum", "w1409_gyesanhada"],
    }),
    defineLesson({
      id: "w14-shopping-money-02",
      stage: "W14",
      title: "Shopping and money II",
      subtitle: "Where to shop",
      goal: "Name common places to shop.",
      newWordIds: ["w1410_gage", "w1411_sijang", "w1412_baekhwajeom", "w1413_pyeonuijeom", "w1405_seil"],
    }),
    defineLesson({
      id: "w14-shopping-money-03",
      stage: "W14",
      title: "Shopping and money III",
      subtitle: "Cheap, expensive, and clerks",
      goal: "Describe price and talk with store staff.",
      newWordIds: ["w1407_ssada", "w1408_bissada", "w1414_sonnim", "w1415_jeomwon", "w1416_palda"],
    }),
    defineLesson({
      id: "w14-shopping-money-04",
      stage: "W14",
      title: "Shopping and money IV",
      subtitle: "Sizes, colors, and returns",
      goal: "Handle receipts, exchanges, and refunds.",
      newWordIds: ["w1406_yeongsujeung", "w1417_saijeu", "w1418_saekkal", "w1419_gyohwanhada", "w1420_hwanbulhada"],
    }),

    defineLesson({
      id: "w15-body-health-01",
      stage: "W15",
      title: "Body and health",
      subtitle: "Parts of the body",
      goal: "Name the parts of your body.",
      newWordIds: ["w1501_mom", "w1502_meori", "w1503_son", "w1504_bal", "w1505_eolgul"],
    }),
    defineLesson({
      id: "w15-body-health-02",
      stage: "W15",
      title: "Body and health II",
      subtitle: "More body parts",
      goal: "Round out body vocabulary.",
      newWordIds: ["w1506_bae", "w1512_mok", "w1513_eokkae", "w1514_heori", "w1518_yeol"],
    }),
    defineLesson({
      id: "w15-body-health-03",
      stage: "W15",
      title: "Body and health III",
      subtitle: "Saying what hurts",
      goal: "Say what hurts and how you got hurt.",
      newWordIds: ["w1507_apeuda", "w1511_dachida", "w1517_nupda", "w1510_gamgi", "w1515_geongang"],
    }),
    defineLesson({
      id: "w15-body-health-04",
      stage: "W15",
      title: "Body and health IV",
      subtitle: "Getting help",
      goal: "Find help and take care of yourself.",
      newWordIds: ["w1508_byeongwon", "w1509_yak", "w1519_yakguk", "w1520_uisa", "w1516_undonghada"],
    }),

    defineLesson({
      id: "w16-weather-nature-01",
      stage: "W16",
      title: "Weather and nature",
      subtitle: "Rain or shine",
      goal: "Talk about today's weather.",
      newWordIds: ["w1601_nalssi", "w1602_bi", "w1603_baram", "w1604_deopda", "w1605_chupda"],
    }),
    defineLesson({
      id: "w16-weather-nature-02",
      stage: "W16",
      title: "Weather and nature II",
      subtitle: "Warm and cool",
      goal: "Describe warm and cool weather.",
      newWordIds: ["w1606_ttatteutada", "w1607_siwonhada", "w1608_haneul", "w1616_nun", "w1617_taeyang"],
    }),
    defineLesson({
      id: "w16-weather-nature-03",
      stage: "W16",
      title: "Weather and nature III",
      subtitle: "The four seasons",
      goal: "Name the seasons of the year.",
      newWordIds: ["w1611_gyejeol", "w1612_bom", "w1613_yeoreum", "w1614_gaeul", "w1615_gyeoul"],
    }),
    defineLesson({
      id: "w16-weather-nature-04",
      stage: "W16",
      title: "Weather and nature IV",
      subtitle: "Sky, sea, and trees",
      goal: "Describe the natural world around you.",
      newWordIds: ["w1609_namu", "w1610_kkot", "w1618_dal", "w1619_byeol", "w1620_bada"],
    }),

    // ── Grammar mechanics track (W17–W19): endings, negation, connectives,
    //    noun modification, honorifics, and irregular families. Additive on
    //    top of the thematic core; taught as grammar roles, not vocabulary.
    defineLesson({
      id: "w17-endings-register-01",
      stage: "W17",
      title: "Polite endings and register",
      subtitle: "Casual, polite, and formal force",
      goal: "Contrast sentence endings by politeness and situation.",
      newWordIds: ["fw1701_a_eo", "fw1702_ayo_eoyo", "fw1703_seumnida", "fw1704_neyo", "fw1705_lkkayo", "fw1706_hada_say"],
      checkpoints: ["ko-to-meaning", "meaning-to-ko", "sentence-blank", "function-usage", "form-recognition", "form-production"],
      pass: { minFirstTryPct: 60, requireTypedAttempt: false },
    }),
    defineLesson({
      id: "w17-tense-negation-01",
      stage: "W17",
      title: "Past tense and negation",
      subtitle: "Not, cannot, and the past",
      goal: "Build basic time and negative sentence meanings.",
      newWordIds: ["fw1711_an", "fw1712_mot", "fw1713_ji_anta", "fw1714_ji_mothada", "fw1715_asseoyo"],
      checkpoints: ["ko-to-meaning", "meaning-to-ko", "sentence-blank", "function-usage", "form-recognition", "form-production"],
      pass: { minFirstTryPct: 60, requireTypedAttempt: false },
    }),
    defineLesson({
      id: "w18-connectives-01",
      stage: "W18",
      title: "Connectives and clause chaining",
      subtitle: "Link clauses naturally",
      goal: "Join short Korean clauses with condition, purpose, and reason.",
      newWordIds: ["fw1801_myeon", "fw1802_reo", "fw1803_geona", "fw1804_jamaja", "fw1805_daga", "fw1806_ttaemune", "w1816_boda_try"],
      checkpoints: ["ko-to-meaning", "meaning-to-ko", "sentence-blank", "function-usage", "form-recognition", "form-production"],
      pass: { minFirstTryPct: 60, requireTypedAttempt: false },
    }),
    defineLesson({
      id: "w18-noun-modification-01",
      stage: "W18",
      title: "Noun modification",
      subtitle: "Forms that sit before a noun",
      goal: "Recognize present, past, future, and adjective modifier forms.",
      newWordIds: ["fw1811_neun_mod", "fw1812_eun_verb", "fw1813_eul_prosp", "fw1814_eun_adj", "fw1815_geot"],
      checkpoints: ["ko-to-meaning", "meaning-to-ko", "sentence-blank", "function-usage", "form-recognition", "form-production"],
      pass: { minFirstTryPct: 60, requireTypedAttempt: false },
    }),
    defineLesson({
      id: "w19-honorifics-01",
      stage: "W19",
      title: "Honorifics",
      subtitle: "Respect the subject, not just the listener",
      goal: "Separate the subject honorific marker from listener politeness.",
      newWordIds: ["fw1901_si", "w1902_gyesida", "w1903_deusida", "w1904_jumusida", "w1905_seongham", "w1906_yeonse"],
      checkpoints: ["ko-to-meaning", "meaning-to-ko", "sentence-blank", "function-usage", "form-recognition", "form-production"],
      pass: { minFirstTryPct: 60, requireTypedAttempt: false },
    }),
    defineLesson({
      id: "w19-irregular-families-01",
      stage: "W19",
      title: "Irregular families",
      subtitle: "Trigger-based sound changes",
      goal: "Treat irregular predicates as predictable trigger families.",
      newWordIds: ["w1911_geotda", "w1912_maepda", "w1913_jitda", "w1914_ppalgata", "w1915_ppareuda", "w1916_salda", "w1917_nada_occur", "w1918_nada_sprout"],
      checkpoints: ["ko-to-meaning", "meaning-to-ko", "sentence-blank", "function-usage", "form-recognition", "form-production"],
      pass: { minFirstTryPct: 60, requireTypedAttempt: false },
    }),
  ];
})();
