#!/usr/bin/env node
// Generate mobile/www from an explicit allowlist of canonical runtime assets.
//
// Capacitor must never point at the repository root: that would package docs,
// audit scripts, Python tooling, and scratch data. This script produces the
// native web payload deterministically and fails loudly when the runtime
// contract is broken (missing referenced asset, unexpected remote dependency).
//
// The service worker (sw.js) is deliberately NOT copied: the native app is
// versioned by installed-app updates, and app.js skips registration when
// running inside Capacitor (see getHanaPathRuntime in app.js).

import { createHash } from "node:crypto";
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, posix, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const mobileRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = join(mobileRoot, "..");
const wwwRoot = join(mobileRoot, "www");
const manifestPath = join(mobileRoot, "www-manifest.json");

// Root files the app loads that are not discoverable from index.html tags
// (fetched at runtime by app.js).
const RUNTIME_FETCHED_FILES = [
  "korean_5000_claude_ready.csv",
  "korean_supplementary_15k.csv",
  "privacy.html",
];

// Directories copied wholesale. audio/ follows the handover §7 parity
// experiment: bundle everything first, measure, then decide.
const RUNTIME_DIRS = ["lib", "icons", "fonts", "audio"];

// Files that must never appear in the native payload, even if a future
// index.html mistakenly references them.
const FORBIDDEN_BASENAMES = new Set(["sw.js"]);

// Dependency-shaped remote references. Bare URLs in comments (license and
// attribution links) are fine; a remote URL in a load position is not.
const REMOTE_DEPENDENCY_PATTERNS = [
  /url\(\s*["']?https?:\/\//i,
  /\bsrc\s*=\s*["']https?:\/\//i,
  /<link\b[^>]*\bhref\s*=\s*["']https?:\/\//i,
  /\bfetch\(\s*["'`]https?:\/\//,
  /\.src\s*=\s*["'`]https?:\/\//,
  /\bimportScripts\(/,
  /\bimport\s+[^;]*\bfrom\s*["']https?:\/\//,
  /\bnew\s+Worker\(\s*["'`]https?:\/\//,
];

function fail(message) {
  console.error(`prepare-web: ERROR ${message}`);
  process.exitCode = 1;
}

function extractIndexAssets(indexHtml) {
  const refs = [];
  for (const match of indexHtml.matchAll(/<link\b[^>]*\bhref=["']([^"']+)["'][^>]*>/gi)) refs.push(match[1]);
  for (const match of indexHtml.matchAll(/<script\b[^>]*\bsrc=["']([^"']+)["'][^>]*><\/script>/gi)) {
    if (/\bdata-browser-only\b/i.test(match[0])) continue;
    refs.push(match[1]);
  }
  return refs;
}

function nativeIndexHtml(indexHtml) {
  return indexHtml.replace(/\s*<!--[^>]*Browser-only GIS adapter[^>]*-->\s*<script\b[^>]*\bdata-browser-only\b[^>]*><\/script>/gi, "");
}

const indexHtml = readFileSync(join(repoRoot, "index.html"), "utf8");
const indexRefs = extractIndexAssets(indexHtml);

for (const ref of indexRefs) {
  if (/^https?:\/\//.test(ref)) {
    fail(`index.html references a remote asset: ${ref} — vendor it locally before packaging`);
  }
}
if (process.exitCode) process.exit(process.exitCode);

// The allowlisted root files: everything index.html references directly
// (with ?v= stripped), plus the runtime-fetched extras, plus index.html.
const rootFiles = new Set(["index.html", ...RUNTIME_FETCHED_FILES]);
for (const ref of indexRefs) {
  const bare = ref.split("?")[0].replace(/^\.\//, "");
  if (!bare || bare.includes("..")) continue;
  const topLevel = bare.split("/")[0];
  if (RUNTIME_DIRS.includes(topLevel)) continue; // covered by directory copy
  rootFiles.add(bare);
}

for (const file of rootFiles) {
  if (FORBIDDEN_BASENAMES.has(posix.basename(file))) {
    fail(`forbidden file would be packaged: ${file}`);
  }
  if (!existsSync(join(repoRoot, file))) {
    fail(`index.html references a missing local file: ${file}`);
  }
}
for (const dir of RUNTIME_DIRS) {
  if (!existsSync(join(repoRoot, dir))) fail(`required runtime directory missing: ${dir}`);
}
if (process.exitCode) process.exit(process.exitCode);

// Rebuild www from scratch, but only if it is the expected generated dir.
if (existsSync(wwwRoot)) {
  if (!existsSync(join(wwwRoot, ".hanapath-generated")) && readdirSync(wwwRoot).length > 0) {
    fail(`refusing to delete ${wwwRoot}: it is not marked as generated output (missing .hanapath-generated)`);
    process.exit(1);
  }
  for (const item of readdirSync(wwwRoot)) {
    rmSync(join(wwwRoot, item), { recursive: true, force: true, maxRetries: 10, retryDelay: 200 });
  }
}
mkdirSync(wwwRoot, { recursive: true });
writeFileSync(join(wwwRoot, ".hanapath-generated"), "Generated by mobile/scripts/prepare-web.mjs. Safe to delete.\n");

for (const file of [...rootFiles].sort()) {
  const target = join(wwwRoot, file);
  mkdirSync(dirname(target), { recursive: true });
  if (file === "index.html") writeFileSync(target, nativeIndexHtml(indexHtml));
  else cpSync(join(repoRoot, file), target);
}
for (const dir of RUNTIME_DIRS) {
  cpSync(join(repoRoot, dir), join(wwwRoot, dir), { recursive: true });
}

// Walk the generated tree: hash every file for the deterministic manifest and
// scan text assets for unexpected remote dependencies.
function walk(dir, out = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name, "en"))) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

const files = walk(wwwRoot);
const manifest = [];
let totalBytes = 0;
const textExtensions = new Set([".html", ".css", ".js", ".mjs", ".json", ".webmanifest", ".svg", ".txt", ".csv"]);

for (const full of files) {
  const rel = relative(wwwRoot, full).split(sep).join("/");
  if (rel === ".hanapath-generated") continue;
  const bytes = readFileSync(full);
  totalBytes += bytes.length;
  manifest.push({ path: rel, bytes: bytes.length, sha256: createHash("sha256").update(bytes).digest("hex") });

  const ext = rel.slice(rel.lastIndexOf(".")).toLowerCase();
  if (textExtensions.has(ext) && !rel.endsWith(".csv")) {
    const text = bytes.toString("utf8");
    for (const pattern of REMOTE_DEPENDENCY_PATTERNS) {
      const match = text.match(pattern);
      if (match) {
        fail(`${rel} contains a remote runtime dependency: ${match[0]}`);
      }
    }
  }
}

manifest.sort((a, b) => a.path.localeCompare(b.path, "en"));
const manifestBody = JSON.stringify({ generatedBy: "mobile/scripts/prepare-web.mjs", fileCount: manifest.length, totalBytes, files: manifest }, null, 1);
writeFileSync(manifestPath, `${manifestBody}\n`);

console.log(`prepare-web: ${manifest.length} files, ${(totalBytes / 1024 / 1024).toFixed(2)} MiB copied to mobile/www`);
console.log(`prepare-web: manifest written to ${relative(repoRoot, manifestPath)}`);
if (process.exitCode) {
  console.error("prepare-web: FAILED — see errors above");
  process.exit(process.exitCode);
}
